// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7MeBf6yDhhYg_aE-JSwuEo_qZgvb__8',
    appId: '1:329479431575:android:7d025accd082f0a28bd0d2',
    messagingSenderId: '329479431575',
    projectId: 'ansechr-ebb38',
    storageBucket: 'ansechr-ebb38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXEjwfxQ-U-JRicI5tqQLFQgxOGjv2vEM',
    appId: '1:329479431575:ios:78d124cf293c136c8bd0d2',
    messagingSenderId: '329479431575',
    projectId: 'ansechr-ebb38',
    storageBucket: 'ansechr-ebb38.firebasestorage.app',
    iosBundleId: 'com.ansechr.careercompass',
  );
}
